### ISSUE TITLE
Closing a file with :q <Shift>zz closes the all tab and exits NVIM

### ISSUE THREAD

**Issue by Trid-collab** [Blacksuan19/init.nvim#11]
Hi, I am newbie to vim/nvim. I across your init.vim file and was following it to put my init.vim file. I noticed that after  put in your Airline plugin configurations in the if I open two files using :e ~/XXX it opens the files in different tabs which I find great but
1. I cannot use the "gt" or "gT" to cycle between the tabs
2. Also when try to a single using :q or :wq or ZZ it closes all tabs and exits nvim
Could you help understand the issue. Is it some configurations I need to do or am I missing something in general

**Comment by Blacksuan19** [comment]
1. `e ~/XXX` opens that file in a new buffer, to cycle between buffers use tab in normal mode
2. to close a buffer use leader + q, `:q` closing everything is default vim behaviour
