### ISSUE TITLE
Migrating to init.lua and Telescope, Native LSP 

### ISSUE THREAD

**Issue by Trid-collab** [Blacksuan19/init.nvim#16]
You have one of the best init.vim I have come across for a learner like me for python setup. I have used you setup in my nvim. Most logical keymaps and setup
Would be migrating this to init.lua with Telescope , nvim native LSP. Have heard it to be fast. I shall look forward to it

**Comment by Blacksuan19** [comment]
Yeah that's in my to do list, native LSP doesn't provide all the features of coc that's why I'm still waiting to find alternatives that keep the experience the same as much as possible
