### ISSUE TITLE
Can't see tabs

### ISSUE THREAD

**Issue by kavin25** [Blacksuan19/init.nvim#17]
Hi, I can't see my tabs of vim, but when i do `:tabs` i get this output
![Screenshot 2021-08-17 at 7 33 26 PM](https://user-images.githubusercontent.com/41034356/129740228-ad28d226-b452-42de-944b-a6b307c19c82.png)

Also I cannot use standard `gt` `gt` to rotate through tabs

**Comment by Blacksuan19** [comment]
Tabs were part of airline which is now removed, you can press leader + b for buffers and i think leader + t should show the tabs
