### ISSUE TITLE
status line wont load any icons..

### ISSUE THREAD

**Issue by sachinoliver** [Blacksuan19/init.nvim#18]
![image](https://user-images.githubusercontent.com/63084488/132989478-ffe6d35c-c69d-4947-8a22-10a4814e8479.png)

**Comment by Blacksuan19** [comment]
Are you using a nerd font?

**Comment by sachinoliver** [comment]
No.

**Comment by Blacksuan19** [comment]
You need a nerd font as outlined in the requirements.

**Comment by sachinoliver** [comment]
OK. Sorry about that.. i didn't see that one... issue got solved. Thanks
