### ISSUE TITLE
Can use bat command --line-range option instead of head

### ISSUE THREAD

**Issue by vipul-sharma20** [Blacksuan19/init.nvim#4]
Saw your floating window thing on reddit. Nice work. I've used your init.nvim to customize some stuff for myself :)

I saw this line:

https://github.com/Blacksuan19/init.nvim/blob/65b70e82d761e3058a7b3c59abe5905343638656/init.vim#L357

You can also use `--line-range` option of `bat` command to achieve the same thing. Just something I wanted to share.

It should then look like this:

```vim
let l:fzf_files_options = '--preview "bat --line-range :'.&lines.' --theme="OneHalfDark" --style=numbers,changes --color always {2..-1}"'
```

**Comment by Blacksuan19** [comment]
Yes that should be better and maybe faster 
Thanks for the insight
