### ISSUE TITLE
Discussion on removing ale

### ISSUE THREAD

**Issue by RonanMacF** [Blacksuan19/init.nvim#5]
Great setup, am a big fan of the config choice.

Based on the readme, `Another example is ThinkVim has a separate extension for formatting while also having ALE which can do that as well, this double functionality is very common, thats one of the things this distro avoids, KISS!`. Is there a need for ale at all considering coc.nvim could do the exact same. Do you think ale has some advantage over coc.nvim?

**Comment by Blacksuan19** [comment]
yes, you're right ALE shouldn't be here
I have plans of replacing it with coc-diagnostic, I still can't replicate some of ALE's functionality with it and that is why it's still present
I am also considering nvim-lsp whenever it is released with 0.5

**Comment by RonanMacF** [comment]
Out of curiosity which features are these that coc is missing? From what I looked into nvim-lsp is a decent alternative but isnt as feature rich as coc.nvim, I believe things like autocomplete wouldnt be available so early days yet.

**Comment by Blacksuan19** [comment]
I could never get autofromatting or fixing on save to work with coc even tho the settings are there, and some other language specific thing like in python ale is faster and in liquid it can properly format liquid inside HTML files 
nvim-lsp does have autocomplete which is provided by the lsp client, but yeah it is still lacking features and it's only on alpha

**Comment by Blacksuan19** [comment]
ALE has been fully replaced so am closing this
