### ISSUE TITLE
why disable netrw?

### ISSUE THREAD

**Issue by ZaynJarvis** [Blacksuan19/init.nvim#7]
Love this setting but I get an empty screen when e.g. `nvim .`.
Just wanna know any specific reason to disable netrw?
`let loaded_netrw = 0`

<img width="682" alt="image" src="https://user-images.githubusercontent.com/31875147/92439072-b598a380-f1dc-11ea-8f2d-e149bf05051c.png">

**Comment by ZaynJarvis** [comment]
is this a netrw issue?

**Comment by Blacksuan19** [comment]
Yup it's because netrw is disabled, I don't see a use case for it since we have fzf which is arguably better

**Comment by ZaynJarvis** [comment]
sure, understand.
In that case, is it possible if we can use fzf windows as default content
when we open a folder with nvim? Feel like it's gonna be cool to do that.

**Comment by Blacksuan19** [comment]
I did have something like that in the past but there were some issues with it and startify, will take another look into it

**Comment by ZaynJarvis** [comment]
awesome thx!
