### ISSUE TITLE
Check out vim-iawriter?

### ISSUE THREAD

**Issue by subnut** [Blacksuan19/init.nvim#8]
I see that you are using amix/vim-zenroom2
Care to check out [vim-iawriter](https://subnut.github.io/vim-iawriter)?

**Comment by Blacksuan19** [comment]
Nice plugin! 
However writers are not one of the targets for this distro, writing in general is beyond the scope of this distro

**Comment by subnut** [comment]
Oops ... I am sorry but the [blogpost](https://blacksuan19.tk/blog/how-to-set-up-nvim) contained it ..... so I thought that this one also does. But on checking the init.vim of this repo, I see that it is very different from the blog post.

Sorry! :sweat:

**Comment by Blacksuan19** [comment]
It's alright, I forgot about the article, might make an updated one since the config has changed a lot
